### ISSUE TITLE
Add ability to change font colours

### ISSUE THREAD

**Issue by MrClyfar** [Microsoft/WhackWhackTerminal#29]
Please forgive me if this is already available, I couldn't see any options to do this when I tried out the terminal.

Because of the colour theme I use in VS (Solarized Light), when I use the Whack Whack terminal, I type out the Powershell cmdlets which appear in a yellow colour. This is very hard to see since the background colour of the terminal is also a light colour due to the theme.

Can the terminal colours be changed? If not, could this be something that is added in a future release please?

**Comment by dgriffen** [comment]
There is a css styling file that can be used to change the font colors for the terminal. You can find an example file [here](https://github.com/Microsoft/WhackWhackTerminal/blob/master/EmbeddedTerminal/view/custom.css). You can choose where this file is located by going to Tools>Options>WhackWhackTerminal and pasting a path to your custom css file. The reason I chose to do it this way instead of an interactive color selector is because the terminal emulator supports 256 colors and having options for all of them would clutter the ui.
