### ISSUE TITLE
Font size incorrect

### ISSUE THREAD

**Issue by juliankay** [Microsoft/WhackWhackTerminal#47]
I assume this is an issue with DPI settings, but after upgrading to Visual Studio 2017 15.6 the custom CSS options have been removed and replaced with a font-size selector that doesn't work.

This is a 10pt font on a Surface Book.
![image](https://user-images.githubusercontent.com/952538/37091392-e1a58ac4-21ff-11e8-8815-ac0ca9c0cca2.png)

**Comment by dgriffen** [comment]
Yeah, there are some unavoidable issues with DPI and WebViews. It wasn't as large an issue before because xterm.js used the DOM to render. They switched to canvas rendering which provides a legend performance boost but DPI gets all messed up. For now I suggest setting the Font size to much larger than you think you need. I have an idea for a fix but it uses some undocumented features and will be a bit difficult to implement.

**Comment by juliankay** [comment]
Yeah, this worked as a temporary fix, however, lots of people switch between docked/undocked situations with different monitor configurations so I foresee this being a bit of a sticking issue.

30pt looked absolutely fine for me when running at the native 200%, but switching back to 100% obviously ended up with a very bad experience.

This is a shame as it is definitely a regression in functionality for me, especially as I'd just got used to having the integrated terminal as part of my workflow.

**Comment by dgriffen** [comment]
Custom css only worked since xterm.js rendered to a DOM. They now render via canvas which doesn't support any css settings. In most configurations this isn't an issue since most browsers respect DPI. It's only the embedded WebViews that seem to have an issue. 

I found a docs page that might potentially hold the fix [here](https://msdn.microsoft.com/en-us/library/mt622670.aspx). That would at least be simpler than the internal APIs I was considering switching to. I'll try that method and see if it works.

**Comment by dgriffen** [comment]
I plan to reintroduce color theming support. Colors had to entirely be redone to support the new version of xterm.js. as a first pass I'll probably just implement a page in the options menu with hex fields.

**Comment by juliankay** [comment]
Looking forward to it! 😁

**Comment by dgriffen** [comment]
As a temporary workaround that doesn't require restarting VS or changing settings you can use `Ctrl +` and `Ctrl -` when you have the terminal selected to zoom and unzoom.
